# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

- name: 'Build and running tests'
  on:
    push:
      branches: '*'
    pull_request:
      branches: '*'
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8 test
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Create test report
        run: surefire-report:report-only -f pom.xml


- name: 'Publish Test Report'
  if: always()
  uses: actions/upload-artifact@v2-preview
  with:
    name: 'test-report'
    path: target/site/surefire-report.html